### ISSUE TITLE
fetch user

### ISSUE THREAD

**Issue by Serhioromano** [stefanvanherwijnen/quasar-app-extension-auth-token-based#1]
I use your extension. еhat looks good. I've learned a lot. Question. 

On every route, change you use user/fetch which calls API. Is that OK? Is this necessary? If I have 1000 apps downloaded and each will request on every call, that is the problem.  Anyway, every API call to get data ш check authorization, why to fetch user?

**Comment by stefanvanherwijnen** [comment]
You are right and this is a bug. I previously used `fetch` to check if the user was logged in, but I forgot to change it in the route guard. I'll find a way to fix it.

**Comment by stefanvanherwijnen** [comment]
https://github.com/stefanvanherwijnen/quasar-app-extension-auth-token-based/commit/8d680bb663df1724222d1ab3c3230fad3c11c175
I released a new version. Closing this for now, let me know if something isn't working.
