### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by ttquoccuong** [stefanvanherwijnen/quasar-app-extension-auth-token-based#3]
Hi Stefan,
In case, we want to use a username with other validate (ex: phonenumber) to login. So can your make it flexible for username?
Sorry, my english is not good.
Thank you so much!

**Comment by stefanvanherwijnen** [comment]
Give this branch a try:
https://github.com/stefanvanherwijnen/quasar-app-extension-auth-token-based/tree/identifier-field

I am not sure how to add extra fields (e.g. phone number) without breaking the basic functionality of the app extension. I'll try to find out if it is possible to inject extra components into a page.

**Comment by stefanvanherwijnen** [comment]
Have a look at the test app for the functionality. You will need to manually add a Register.vue page and route to your app to overwrite the default one.

Feel free to reopen if it does not work like it should.
